server:
  port: 9999

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER:127.0.0.1}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
