spring:
  application:
    name: service-discovery
  flyway:
    enabled: false

server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
